name: tareeqi
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  http: ^1.6.0
  image_picker: ^1.2.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  country_picker: ^2.0.27
  tflite_flutter: ^0.12.1
  image: ^4.8.0
  flutter_map_marker_cluster: ^1.3.6
  flutter_map_heatmap: ^0.0.7
  intl_phone_field: ^3.2.0
  google_fonts: ^8.0.2
  camera: ^0.12.0+1
  shared_preferences: ^2.5.5
  vibration: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

# هاد القسم لازم يكون مستقل تماماً وما في قبله مسافات
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.webp"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon.webp"

flutter:
  uses-material-design: true
  assets:
    - assets/best_float32.tflite
    - assets/classes.txt
    - assets/icon.webp